package ist.alchm.smthsHub.debug;

public enum Verdict {
    FLOODGATE_TANIMIYOR,
    FLOODGATE_DINLEYICISI_YOK,
    FORM_GONDERILMEDI,
    CEVAP_BACKENDE_ULASMADI,
    PACKETEVENTS_IPTAL,
    DECODER_ONCESI_KAYIP,
    PROTOCOLLIB_IPTAL,
    BUKKIT_ONCESI_KAYIP,
    FLOODGATE_ESLESTIRMEDI,
    SAGLAM,
    OLCULEMEDI
}
