package ist.alchm.smthsHub.debug;

public enum Verdict {
    JAVA_OYUNCU,
    PROXY_FLOODGATE_VERISI_YOK,
    BACKEND_FLOODGATE_OKUMUYOR,
    HANDSHAKE_SAGLAM,
    FORM_GONDERILMEDI,
    CEVAP_BACKENDE_ULASMADI,
    PACKETEVENTS_IPTAL,
    DECODER_ONCESI_KAYIP,
    PROTOCOLLIB_IPTAL,
    BUKKIT_ONCESI_KAYIP,
    SMTHSHUB_ESLESMEDI,
    AKSIYON_HATASI,
    SAGLAM,
    OLCULEMEDI
}
